# to create cluster:
#   $ kind create cluster --config ./kind/cluster.yaml --name=kind-cluster
# to delete cluster:
#   $ kind delete cluster --name=kind-cluster

apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 50080
        protocol: TCP
  - role: worker
  - role: worker
