apiVersion: apps/v1
kind: Deployment

metadata:
  name: rackapp-deployment
  labels:
    app.kubernetes.io/name: rackapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rackapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rackapp
    spec:
      containers:
        - name: rackapp-container
          image: rackapp-image:1
          imagePullPolicy: Never
          ports:
            - containerPort: 9292
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rackapp
