apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: rackapp-ingress
  labels:
    app.kubernetes.io/name: rackapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rackapp-service
                port:
                  number: 19292
