apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: rackapp-ingress

spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: rackapp-service
              servicePort: 19292
